# Generated by Django 2.2 on 2019-04-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='todo_item',
            new_name='list_name',
        ),
    ]
