# Generated by Django 2.2 on 2019-05-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20190425_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_name',
            field=models.CharField(max_length=30),
        ),
    ]
